# Generated by Django 4.2.3 on 2023-08-17 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tg_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Indirizzo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True, verbose_name='Gruppo sanguigno')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Data di iscrizione')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, verbose_name='Numero di telefono')),
                ('clothes_size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Taglia abbigliamento')),
                ('shoe_size', models.IntegerField(blank=True, null=True, verbose_name='Numero di scarpe')),
                ('illnesses', models.TextField(blank=True, null=True, verbose_name='Malattie')),
                ('workplace_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Azienda')),
                ('workplace_vat', models.CharField(blank=True, max_length=11, null=True, verbose_name='Azienda - Partita IVA')),
                ('workplace_address', models.TextField(blank=True, null=True, verbose_name='Azienda - Indirizzo')),
                ('workplace_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Azienda - Numero di telefono')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('fkuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('telegram_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tg_bot.telegramuser')),
            ],
            options={
                'indexes': [models.Index(fields=['fkuser'], name='core_profil_fkuser__543716_idx')],
            },
        ),
    ]
