# Generated by Django 4.2.3 on 2023-07-31 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('blood_type', models.CharField(max_length=3, null=True)),
                ('join_date', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('telegram_user_id', models.CharField(max_length=20, null=True)),
                ('fkuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['fkuser'], name='core_profil_fkuser__543716_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('fkuser',), name='one_profile_per_user'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('telegram_user_id',), name='one_telegram_per_person'),
        ),
    ]
