# Generated by Django 4.2.3 on 2023-07-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
