# -*- coding: utf-8 -*-
# pylint: disable=missing-module-docstring,invalid-name,missing-function-docstring,unused-argument,missing-class-docstring
# Generated by Django 4.0.5 on 2022-07-25 15:32

from django.contrib.auth.models import Group, Permission
from django.db import migrations


def add_default_groups(apps, schema_editor):
    volunteer_group, _ = Group.objects.get_or_create(name='Volontario')

def remove_default_groups(apps, schema_editor):
    volunteer_group = Group.objects.get('Volontario')

    volunteer_group.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_save_permissions'),
    ]

    operations = [
        migrations.RunPython(add_default_groups, remove_default_groups)
    ]
