# Generated by Django 4.2.3 on 2023-07-31 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_telegram_user_id_alter_profile_fkuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramlink',
            name='fkuser',
        ),
        migrations.AddField(
            model_name='telegramlink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='telegramlink',
            name='telegram_user',
            field=models.CharField(default='aa', max_length=20),
            preserve_default=False,
        ),
    ]
