# Generated by Django 4.2.3 on 2023-07-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_telegramlink_fkuser_telegramlink_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['fkuser'], name='core_profil_fkuser__543716_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('fkuser',), name='one_profile_per_user'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('telegram_user_id',), name='one_telegram_per_person'),
        ),
    ]
