# Generated by Django 4.2.3 on 2023-08-02 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pcroncellobot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_code', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('telegram_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pcroncellobot.telegramuser')),
            ],
        ),
    ]
