# Generated by Django 6.0.1 on 2026-01-20 21:39

import django.db.models.deletion
import tg_bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volontario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volontario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to='volontario.volontario')),
            ],
            options={
                'verbose_name': 'Utente Telegram',
                'verbose_name_plural': 'Utenti Telegram',
            },
        ),
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('token', models.CharField(default=tg_bot.models.generate_login_token, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_tokens', to='tg_bot.telegramuser')),
            ],
            options={
                'verbose_name': 'Token di Login',
                'verbose_name_plural': 'Token di Login',
            },
        ),
        migrations.CreateModel(
            name='WebLoginRequest',
            fields=[
                ('token', models.CharField(default=tg_bot.models.generate_login_token, max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('approved', 'Approvato'), ('denied', 'Rifiutato'), ('expired', 'Scaduto')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_login_requests', to='tg_bot.telegramuser')),
                ('volontario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_login_requests', to='volontario.volontario')),
            ],
            options={
                'verbose_name': 'Richiesta Login Web',
                'verbose_name_plural': 'Richieste Login Web',
            },
        ),
    ]
