# Generated by Django 6.0.1 on 2026-01-17 11:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
        ('volontario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('clock_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volontario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='volontario.volontario')),
            ],
            options={
                'verbose_name': 'Registrazione Ore',
                'verbose_name_plural': 'Registrazioni Ore',
                'ordering': ['-clock_in'],
            },
        ),
    ]
