# Generated by Django 6.0.1 on 2026-01-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_alter_telegramuser_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='chat_id',
        ),
    ]
