# Generated by Django 6.0.5 on 2026-07-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_remove_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllertaMeteoStato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_istat_comune', models.CharField(max_length=6)),
                ('cd_tipologia_gis', models.IntegerField()),
                ('nome_zona', models.CharField(blank=True, max_length=128)),
                ('codice_zona', models.CharField(blank=True, max_length=32)),
                ('cd_livello', models.IntegerField(default=0)),
                ('livello', models.CharField(blank=True, max_length=64)),
                ('notified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stato Allerta Meteo',
                'verbose_name_plural': 'Stati Allerta Meteo',
                'unique_together': {('cd_istat_comune', 'cd_tipologia_gis')},
            },
        ),
    ]
