# Generated by Django 6.0.1 on 2026-01-20 17:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volontario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('nome', models.CharField(max_length=150)),
                ('poll_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('poll_message_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Servizio',
                'verbose_name_plural': 'Servizi',
            },
        ),
        migrations.CreateModel(
            name='Timbratura',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('clock_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fkservizio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servizio.servizio')),
                ('fkvolontario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='volontario.volontario')),
            ],
            options={
                'verbose_name': 'Registrazione Ore',
                'verbose_name_plural': 'Registrazioni Ore',
                'ordering': ['-clock_in'],
            },
        ),
        migrations.CreateModel(
            name='VolontarioServizioMap',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('risposta', models.CharField(blank=True, choices=[('si', 'Sì'), ('no', 'No'), ('forse', 'Forse')], max_length=10, null=True)),
                ('risposta_at', models.DateTimeField(blank=True, null=True)),
                ('fkservizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servizio.servizio')),
                ('fkvolontario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volontario.volontario')),
            ],
            options={
                'verbose_name': 'Disponibilità Volontario',
                'verbose_name_plural': 'Disponibilità Volontari',
                'unique_together': {('fkvolontario', 'fkservizio')},
            },
        ),
        migrations.AddField(
            model_name='servizio',
            name='volontari',
            field=models.ManyToManyField(through='servizio.VolontarioServizioMap', to='volontario.volontario'),
        ),
    ]
