# Generated by Django 6.0.1 on 2026-02-13 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServizioType',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo Servizio',
                'verbose_name_plural': 'Tipi Servizio',
            },
        ),
        migrations.AddField(
            model_name='servizio',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servizio.serviziotype'),
        ),
    ]
