# Generated by Django 6.0.1 on 2026-02-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizio', '0002_serviziotype_servizio_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizio',
            name='send_message',
            field=models.BooleanField(default=True),
        ),
    ]
