# Generated by Django 6.0.1 on 2026-02-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizio', '0003_servizio_send_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizio',
            name='poll_closed',
            field=models.BooleanField(default=False),
        ),
    ]
