# Generated by Django 6.0.1 on 2026-02-13 18:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizio', '0004_servizio_poll_closed'),
        ('volontario', '0002_alter_volontario_codice_fiscale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=300)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('servizio_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_template_items', to='servizio.serviziotype')),
            ],
            options={
                'verbose_name': 'Elemento Checklist Template',
                'verbose_name_plural': 'Elementi Checklist Template',
                'ordering': ['ordine', 'descrizione'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descrizione', models.TextField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('notification_sent', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servizio.serviziotype')),
                ('volontari', models.ManyToManyField(blank=True, related_name='scheduled_tasks', to='volontario.volontario')),
            ],
            options={
                'verbose_name': 'Attivita Programmata',
                'verbose_name_plural': 'Attivita Programmate',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=300)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('completato', models.BooleanField(default=False)),
                ('completato_at', models.DateTimeField(blank=True, null=True)),
                ('completato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='volontario.volontario')),
                ('scheduled_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='servizio.scheduledtask')),
            ],
            options={
                'verbose_name': 'Elemento Checklist',
                'verbose_name_plural': 'Elementi Checklist',
                'ordering': ['ordine', 'descrizione'],
            },
        ),
        migrations.AddField(
            model_name='timbratura',
            name='fkscheduled_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timbrature', to='servizio.scheduledtask'),
        ),
        migrations.AddConstraint(
            model_name='timbratura',
            constraint=models.CheckConstraint(condition=models.Q(('fkservizio__isnull', False), ('fkscheduled_task__isnull', False), _negated=True), name='timbratura_single_link'),
        ),
    ]
