# Generated by Django 6.0.1 on 2026-02-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizio', '0005_checklisttemplateitem_scheduledtask_checklistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timbratura',
            name='checklist_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
