# Generated by Django 6.0.3 on 2026-03-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizio', '0009_servizio_end_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizio',
            name='poll_close_date',
            field=models.DateTimeField(blank=True, help_text='When to close the poll (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='volontarioserviziomap',
            name='risposta',
            field=models.CharField(blank=True, choices=[('si', 'Sì'), ('no', 'No')], max_length=10, null=True),
        ),
    ]
