# Generated by Django 6.0.1 on 2026-01-14 09:49

import django.db.models.deletion
import uuid
import volontario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizzazione',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOggetto',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVeicolo',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BaseOggetto',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descrizione', models.TextField()),
                ('fkorganizzazione', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volontario.organizzazione')),
            ],
        ),
        migrations.CreateModel(
            name='Volontario',
            fields=[
                ('codice_fiscale', volontario.models.CodiceFiscaleField(max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('fkorganizzazione', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volontario.organizzazione')),
            ],
        ),
        migrations.CreateModel(
            name='Oggetto',
            fields=[
                ('baseoggetto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='volontario.baseoggetto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volontario.tipooggetto')),
            ],
            bases=('volontario.baseoggetto',),
        ),
        migrations.CreateModel(
            name='Veicolo',
            fields=[
                ('baseoggetto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='volontario.baseoggetto')),
                ('targa', models.CharField(max_length=12)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volontario.tipoveicolo')),
            ],
            bases=('volontario.baseoggetto',),
        ),
    ]
