# Generated by Django 6.0.1 on 2026-01-20 17:33

import django.db.models.deletion
import uuid
import volontario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificazione',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Certificazione',
                'verbose_name_plural': 'Certificazioni',
            },
        ),
        migrations.CreateModel(
            name='Organizzazione',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Organizzazione',
                'verbose_name_plural': 'Organizzazioni',
            },
        ),
        migrations.CreateModel(
            name='TipoOggetto',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo Oggetto',
                'verbose_name_plural': 'Tipi Oggetto',
            },
        ),
        migrations.CreateModel(
            name='TipoVeicolo',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo Veicolo',
                'verbose_name_plural': 'Tipi Veicolo',
            },
        ),
        migrations.CreateModel(
            name='Oggetto',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descrizione', models.TextField(blank=True)),
                ('fkorganizzazione', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volontario.organizzazione', verbose_name='Organizzazione')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volontario.tipooggetto')),
            ],
            options={
                'verbose_name': 'Oggetto',
                'verbose_name_plural': 'Oggetti',
            },
        ),
        migrations.CreateModel(
            name='Veicolo',
            fields=[
                ('targa', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('descrizione', models.TextField(blank=True)),
                ('fkorganizzazione', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volontario.organizzazione', verbose_name='Organizzazione')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volontario.tipoveicolo')),
            ],
            options={
                'verbose_name': 'Veicolo',
                'verbose_name_plural': 'Veicoli',
            },
        ),
        migrations.CreateModel(
            name='Volontario',
            fields=[
                ('codice_fiscale', volontario.models.CodiceFiscaleField(max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('fkorganizzazione', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volontario.organizzazione', verbose_name='Organizzazione')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volontario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Volontario',
                'verbose_name_plural': 'Volontari',
            },
        ),
        migrations.CreateModel(
            name='CertificazioneVolontarioMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conseguimento', models.DateField()),
                ('fkcertificazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volontario.certificazione')),
                ('fkvolontario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volontario.volontario')),
            ],
            options={
                'verbose_name': 'Certificazione Volontario',
                'verbose_name_plural': 'Certificazioni Volontari',
            },
        ),
        migrations.AddField(
            model_name='certificazione',
            name='volontari',
            field=models.ManyToManyField(through='volontario.CertificazioneVolontarioMap', to='volontario.volontario'),
        ),
    ]
