# Generated by Django 6.0.1 on 2026-01-21 20:04

import django.db.models.functions.text
import volontario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volontario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='volontario',
            name='codice_fiscale',
            field=volontario.models.CodiceFiscaleField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='volontario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('codice_fiscale'), name='unique_codice_fiscale_case_insensitive'),
        ),
    ]
