# Generated by Django 6.0.1 on 2026-01-15 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volontario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificazione',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CertificazioneVolontarioMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conseguimento', models.DateField()),
                ('fkcertificazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volontario.certificazione')),
                ('fkvolontario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volontario.volontario')),
            ],
        ),
        migrations.AddField(
            model_name='certificazione',
            name='volontari',
            field=models.ManyToManyField(through='volontario.CertificazioneVolontarioMap', to='volontario.volontario'),
        ),
    ]
