# Generated by Django 6.0.1 on 2026-01-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volontario', '0002_certificazione_certificazionevolontariomap_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificazione',
            options={'verbose_name': 'Certificazione', 'verbose_name_plural': 'Certificazioni'},
        ),
        migrations.AlterModelOptions(
            name='certificazionevolontariomap',
            options={'verbose_name': 'Certificazione Volontario', 'verbose_name_plural': 'Certificazioni Volontari'},
        ),
        migrations.AlterModelOptions(
            name='oggetto',
            options={'verbose_name': 'Oggetto', 'verbose_name_plural': 'Oggetti'},
        ),
        migrations.AlterModelOptions(
            name='organizzazione',
            options={'verbose_name': 'Organizzazione', 'verbose_name_plural': 'Organizzazioni'},
        ),
        migrations.AlterModelOptions(
            name='tipooggetto',
            options={'verbose_name': 'Tipo Oggetto', 'verbose_name_plural': 'Tipi Oggetto'},
        ),
        migrations.AlterModelOptions(
            name='tipoveicolo',
            options={'verbose_name': 'Tipo Veicolo', 'verbose_name_plural': 'Tipi Veicolo'},
        ),
        migrations.AlterModelOptions(
            name='veicolo',
            options={'verbose_name': 'Veicolo', 'verbose_name_plural': 'Veicoli'},
        ),
        migrations.AlterModelOptions(
            name='volontario',
            options={'verbose_name': 'Volontario', 'verbose_name_plural': 'Volontari'},
        ),
        migrations.AlterField(
            model_name='oggetto',
            name='fkorganizzazione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volontario.organizzazione', verbose_name='Organizzazione'),
        ),
        migrations.AlterField(
            model_name='veicolo',
            name='fkorganizzazione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volontario.organizzazione', verbose_name='Organizzazione'),
        ),
        migrations.AlterField(
            model_name='volontario',
            name='fkorganizzazione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='volontario.organizzazione', verbose_name='Organizzazione'),
        ),
    ]
