# Generated by Django 6.0.1 on 2026-02-22 20:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servizio', '0006_add_checklist_message_id_to_timbratura'),
        ('volontario', '0002_alter_volontario_codice_fiscale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDotazione',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo Dotazione',
                'verbose_name_plural': 'Tipi Dotazione',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Dotazione',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('taglia', models.CharField(blank=True, max_length=10)),
                ('data_assegnazione', models.DateField()),
                ('data_restituzione', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('volontario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotazioni', to='volontario.volontario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assegnazioni', to='magazzino.tipodotazione')),
            ],
            options={
                'verbose_name': 'Dotazione',
                'verbose_name_plural': 'Dotazioni',
                'ordering': ['-data_assegnazione'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoServizioType',
            fields=[
                ('pkid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('servizio_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiti_dotazione', to='servizio.serviziotype')),
                ('tipo_dotazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servizi_richiesti', to='magazzino.tipodotazione')),
            ],
            options={
                'verbose_name': 'Requisito Dotazione Servizio',
                'verbose_name_plural': 'Requisiti Dotazione Servizio',
                'unique_together': {('servizio_type', 'tipo_dotazione')},
            },
        ),
    ]
