# Generated by Django 4.2.3 on 2023-07-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servizioresponse',
            name='response',
            field=models.IntegerField(choices=[(1, 'Accettato'), (2, 'Rifiutato'), (3, 'Forse')]),
        ),
    ]
