# Generated by Django 4.2.3 on 2024-05-26 17:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servizio', '0003_remove_servizioresponse_poll_id_servizio_poll_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timbratura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_begin', models.DateTimeField(default=datetime.datetime.now)),
                ('datetime_end', models.DateTimeField(blank=True, null=True)),
                ('fkservizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servizio.servizio')),
                ('fkuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
