# Generated by Django 5.0.6 on 2024-05-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servizio', '0004_timbratura'),
    ]

    operations = [
        migrations.AddField(
            model_name='timbratura',
            name='message_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
