# Generated by Django 4.2.3 on 2023-08-13 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Modello')),
                ('brand', models.CharField(max_length=20, verbose_name='Marca')),
                ('kind', models.CharField(max_length=20, verbose_name='Tipo')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('conditions', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Condizioni')),
                ('notes', models.TextField(verbose_name='Note aggiuntive')),
            ],
        ),
    ]
