# Generated by Django 4.2.3 on 2024-02-11 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('organizer', models.CharField(max_length=50, verbose_name='Organizzatore')),
                ('fkcertification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='certifications.certification')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Inizio')),
                ('end_date', models.DateTimeField(verbose_name='Fine')),
                ('class_type', models.IntegerField(choices=[(1, 'Lezione'), (2, 'Addestramento')], verbose_name='Tipo di lezione')),
                ('uniform_required', models.BooleanField(verbose_name='Divisa richiesta?')),
                ('equipment_required', models.ManyToManyField(blank=True, null=True, to='hr.personalequipmenttype', verbose_name='Equipaggiamento richiesto')),
                ('fktrainingcourse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='certifications.trainingcourse')),
            ],
        ),
    ]
