# Generated by Django 4.2.3 on 2024-02-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_default_user_groups'),
        ('hr', '0001_initial'),
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingclass',
            name='equipment_required',
            field=models.ManyToManyField(blank=True, to='hr.personalequipmenttype', verbose_name='Equipaggiamento richiesto'),
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_completed', models.BooleanField()),
                ('fktrainingcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certifications.trainingcourse')),
                ('fkuserprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
